repo_url: https://github.com/FelipeFreire-gf/compiladores.git
repo_name: 2025.1 - Os CobraCai 

site_name: CobraCai - Compiladores 1

nav:
  #- Landing Page: landing.html
  - Home: index.md

  - Planejamento: 
      - Introdução: "documento-planejamento/documento-planejamento.md"
      - HeatMap: "documento-planejamento/heatmap.md"
      - Cronograma Planejado: "documento-planejamento/cronograma-planejado.md"
      - Cronograma Executado: "documento-planejamento/cronograma-executado.md"
      - Ferramentas: "documento-planejamento/ferramentas-utilizadas.md"
      - Metodologia: "documento-planejamento/metodologias-utilizadas.md"
      
  - Atas:
        - Ata Reunião 1: "atas-reuniao/ata-reuniao-1.md"
        - Ata Reunião 2: "atas-reuniao/ata-reuniao-2.md"
        - Ata Reunião 3: "atas-reuniao/ata-reuniao-3.md"
        - Ata Reunião 4: "atas-reuniao/ata-reuniao-4.md"
        - Ata Reunião 5: "atas-reuniao/ata-reuniao-5.md"
        - Ata Reunião 6: "atas-reuniao/ata-reunicao-6.md"  
        - Ata Reunião 7: "atas-reuniao/ata-reuniao-7.md"
        - Ata Reunião 8: "atas-reuniao/ata-reuniao-8.md"
        - Ata Reunião 9: "atas-reuniao/ata-reuniao-9.md"
        - Ata Reunião 10: "atas-reuniao/ata-reuniao-10.md"  

  - Atividades Desenvolvidas em Aula: 
      - Projeto Aula 1: "documento-aula/documento-aula1.md"    
      - Projeto Aula 2: "documento-aula/documento-aula2.md" 
      - Projeto Aula 3: "documento-aula/documento-aula3.md" 
      - Projeto Aula 4: "documento-aula/documento-aula4.md" 
      - Projeto Aula 5: "documento-aula/documento-aula5.md" 
      - Projeto Aula 6: "documento-aula/documento-aula6.md" 
      - Projeto Aula 7: "documento-aula/documento-aula7.md" 
      - Projeto Aula 8: "documento-aula/documento-aula8.md" 
      - Projeto Aula 9: "documento-aula/documento-aula9.md"
      - Projeto Aula 10: "documento-aula/documento-aula10.md"  

  - Entregas:
    - Entrega 1: "entregas/entregas1.md" 
    - Entrega 2: "entregas/entregas2.md" 
    - Entrega 3: "entregas/entregas3.md" 
  

theme:
  logo: assets/logoSemFundo.ico
  font:
    text: Montserrat
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/git-alt
